"""update vehicle

Revision ID: 1195cf6e6157
Revises: 711e347c56e2
Create Date: 2020-06-28 02:07:21.676339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1195cf6e6157'
down_revision = '711e347c56e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('preventative_maintenance_interval', sa.Integer(), nullable=True))
    op.drop_column('vehicle', 'preventative_mainterance_interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('preventative_mainterance_interval', sa.INTEGER(), nullable=True))
    op.drop_column('vehicle', 'preventative_maintenance_interval')
    # ### end Alembic commands ###
