"""added Vehicle table

Revision ID: 711e347c56e2
Revises: 3d758b9f1290
Create Date: 2020-06-28 02:02:07.910781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711e347c56e2'
down_revision = '3d758b9f1290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('costno', sa.String(length=4), nullable=False),
    sa.Column('grease_interval', sa.Integer(), nullable=True),
    sa.Column('oil_change_interval', sa.Integer(), nullable=True),
    sa.Column('preventative_mainterance_interval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('costno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
